"""Auto-installed SpoolTap dashboard (storage mode).

Ports the tested layout (ha/dashboards/spooltap-v2.yaml, generated by
efforts/v2-workflow/dashboard_setup.py and proven on the dev box) onto the v0.2.0
native entities, and installs it programmatically so a HACS install is one-click.

HA has no public API for integrations to create dashboards, so the installer uses
the same internal path the frontend's own `lovelace/dashboards/create` WS command
takes (verified against HA 2026.6.4 source, byte-identical to current dev):
core's live DashboardsCollection -> async_create_item (its CHANGE_ADDED listener
synchronously creates the LovelaceStorage and registers the sidebar panel) ->
LovelaceStorage.async_save(config). Everything is guarded — a failure here must
never fail entry setup; `spooltap.install_dashboard` (force: true) is the
recovery/refresh lever.

Frontend prerequisites (HACS Frontend, not installable from an integration):
Mushroom (`custom:mushroom-template-card`) + card-mod.
"""

from __future__ import annotations

import logging
from typing import Any

from homeassistant.core import HomeAssistant

_LOGGER = logging.getLogger(__name__)

DASHBOARD_URL_PATH = "spooltap-v2"  # storage url_paths must contain a hyphen
DASHBOARD_TITLE = "SpoolTap"
DASHBOARD_ICON = "mdi:printer-3d-nozzle"

_MODE_COLORS = {"Assign": "blue", "Bind": "green", "Modify": "amber", "Spools": "purple"}
_MODE_ICONS = {
    "Assign": "mdi:tray-arrow-down",
    "Bind": "mdi:link-variant",
    "Modify": "mdi:pencil",
    "Spools": "mdi:format-list-bulleted",
}


def _press(button_entity: str) -> dict[str, Any]:
    """tap_action that presses one of the integration's button entities."""
    return {
        "action": "perform-action",
        "perform_action": "button.press",
        "target": {"entity_id": button_entity},
    }


def _mode_chip(mode: str) -> dict[str, Any]:
    color = _MODE_COLORS[mode]
    return {
        "type": "custom:mushroom-template-card",
        "primary": mode,
        "icon": _MODE_ICONS[mode],
        "layout": "vertical",
        "icon_color": (
            f"{{{{ '{color}' if is_state('select.spooltap_mode','{mode}') else 'disabled' }}}}"
        ),
        "tap_action": {
            "action": "perform-action",
            "perform_action": "select.select_option",
            "target": {"entity_id": "select.spooltap_mode"},
            "data": {"option": mode},
        },
        "card_mod": {
            "style": (
                "ha-card { border-radius: 14px; box-shadow: none; "
                f"{{% if is_state('select.spooltap_mode','{mode}') %}} "
                f"background: rgba(var(--rgb-{color}),0.20); "
                f"border: 2px solid rgba(var(--rgb-{color}),0.75); "
                "{% else %} opacity: 0.45; border: 2px solid transparent; {% endif %} }"
            )
        },
    }


def _refresh_button(color: str) -> dict[str, Any]:
    return {
        "type": "button",
        "name": "Refresh",
        "icon": "mdi:refresh",
        "show_state": False,
        "tap_action": _press("button.spooltap_refresh"),
        "card_mod": {
            "style": f"ha-card {{ --card-mod-icon-color: rgba(var(--rgb-{color}),1); }}"
        },
    }


_HEADER_CARD = {
    "type": "custom:mushroom-template-card",
    # Keep the primary SHORT (mushroom renders it on one non-wrapping line) —
    # the status message lives in the multiline secondary so it can never
    # truncate. Context bits (tag in hand / armed slot / assign result) appear
    # on a second line only when they actually say something.
    "primary": (
        "{{ states('select.spooltap_mode') }} mode"
        "{% if states('sensor.spooltap_assign_result') == 'Working' %} · working…"
        "{% elif states('sensor.spooltap_assign_result') == 'Failed' %} · failed"
        "{% endif %}"
    ),
    "secondary": (
        "{% set s = states('sensor.spooltap_status') %}"
        "{{ s if s not in ['unknown', 'unavailable', ''] "
        "else 'Ready — tap a slot tag, or use the dropdowns below.' }}"
        "{% set role = state_attr('sensor.spooltap_tag_in_hand','role') %}"
        "{% set detail = state_attr('sensor.spooltap_tag_in_hand','detail') %}"
        "{% set pend = state_attr('sensor.spooltap_assign_result','pending_slot_label') %}"
        "{% set bits = [] %}"
        "{% if role in ['spool','slot'] %}"
        "{% set bits = bits + ['in hand: ' ~ (detail or role)] %}"
        "{% elif role == 'unbound' %}"
        "{% set bits = bits + ['in hand: unbound tag'] %}"
        "{% endif %}"
        "{% if pend %}{% set bits = bits + ['armed: ' ~ pend] %}{% endif %}"
        "{% if bits %}\n{{ bits | join('  ·  ') }}{% endif %}"
    ),
    "icon": (
        "{{ {'Assign':'mdi:tray-arrow-down','Bind':'mdi:link-variant',"
        "'Modify':'mdi:pencil','Spools':'mdi:format-list-bulleted'}"
        ".get(states('select.spooltap_mode'),'mdi:nfc-variant') }}"
    ),
    "icon_color": (
        "{{ {'Assign':'blue','Bind':'green','Modify':'amber','Spools':'purple'}"
        ".get(states('select.spooltap_mode'),'grey') }}"
    ),
    "multiline_secondary": True,
    "card_mod": {
        # The nested key pierces mushroom's shadow DOM: bump the secondary (the
        # status text) to a readable size — it is the card's real payload.
        "style": {
            ".": (
                "ha-card { border-radius: 14px; border-left: 6px solid rgba(var(--rgb-"
                "{{ {'Assign':'blue','Bind':'green','Modify':'amber','Spools':'purple'}"
                ".get(states('select.spooltap_mode'),'grey') }}),0.9); }"
            ),
            "mushroom-state-info$": (
                ".secondary { font-size: 13.5px !important; line-height: 1.45 "
                "!important; white-space: pre-line !important; }"
            ),
        }
    },
}


def _mode_section(mode: str, cards: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "type": "grid",
        "column_span": 1,
        "visibility": [
            {"condition": "state", "entity": "select.spooltap_mode", "state": mode}
        ],
        "cards": [
            {
                "type": "heading",
                "heading": mode,
                "icon": _MODE_ICONS[mode],
                "heading_style": "title",
            },
            *cards,
        ],
    }


_ASSIGN_CARDS: list[dict[str, Any]] = [
    {
        "type": "markdown",
        "content": (
            "Tap a **slot tag** then a **spool tag**, _or_ use the dropdowns. Assigning "
            "writes Bambuddy and (printer online) configures the AMS tray."
        ),
    },
    {
        "type": "entities",
        "entities": [
            {
                "entity": "sensor.spooltap_assign_result",
                "type": "attribute",
                "attribute": "pending_slot_label",
                "name": "Pending slot",
            }
        ],
    },
    {
        "type": "horizontal-stack",
        "cards": [
            {
                "type": "button",
                "name": "Cancel Assignment",
                "icon": "mdi:cancel",
                "show_state": False,
                "tap_action": _press("button.spooltap_cancel"),
                "card_mod": {
                    "style": "ha-card { --card-mod-icon-color: rgba(var(--rgb-red),1); }"
                },
            },
            _refresh_button("blue"),
        ],
    },
    {
        "type": "heading",
        "heading": "Manual assign (no scan)",
        "heading_style": "subtitle",
        "icon": "mdi:cursor-default-click",
    },
    {
        "type": "entities",
        "entities": [
            {"entity": "select.spooltap_assign_slot", "name": "Slot"},
            {"entity": "select.spooltap_assign_brand", "name": "Brand"},
            {"entity": "select.spooltap_assign_type", "name": "Type"},
            {"entity": "select.spooltap_assign_spool", "name": "Spool (unassigned)"},
        ],
    },
    {
        "type": "button",
        "name": "Assign spool → slot",
        "icon": "mdi:tray-arrow-down",
        "show_state": False,
        "tap_action": _press("button.spooltap_assign"),
        "card_mod": {
            "style": "ha-card { --card-mod-icon-color: rgba(var(--rgb-blue),1); }"
        },
    },
]

_BIND_CARDS: list[dict[str, Any]] = [
    {
        "type": "horizontal-stack",
        "cards": [
            {
                "type": "entities",
                "entities": [
                    {
                        "entity": "switch.spooltap_bind_mode",
                        "name": "Bind Mode (ON to register)",
                    }
                ],
            },
            _refresh_button("green"),
        ],
    },
    {
        "type": "markdown",
        "content": (
            "Turn **Bind Mode ON**, give a tag (scan · pick from registry · paste a UID), "
            "pick a spool **or** a slot, then Bind. Bind Mode auto-clears when you leave "
            "this tab."
        ),
    },
    {
        "type": "entities",
        "entities": [
            {"entity": "select.spooltap_bind_tag", "name": "Tag from registry"},
            {"entity": "text.spooltap_tag_input", "name": "…or paste a Tag UID"},
        ],
        "title": "Tag source",
    },
    {
        "type": "heading",
        "heading": "Bind tag → spool",
        "heading_style": "subtitle",
        "icon": "mdi:nfc-tap",
    },
    {
        "type": "entities",
        "entities": [
            {"entity": "select.spooltap_bind_pool", "name": "Pool"},
            {"entity": "select.spooltap_bind_brand", "name": "Brand"},
            {"entity": "select.spooltap_bind_type", "name": "Type"},
            {"entity": "select.spooltap_bind_spool", "name": "Spool"},
        ],
    },
    {
        "type": "button",
        "name": "Bind Tag to Spool",
        "icon": "mdi:link-variant-plus",
        "show_state": False,
        "tap_action": _press("button.spooltap_bind_spool"),
        "card_mod": {
            "style": "ha-card { --card-mod-icon-color: rgba(var(--rgb-green),1); }"
        },
    },
    {
        "type": "heading",
        "heading": "Bind tag → slot",
        "heading_style": "subtitle",
        "icon": "mdi:tray-plus",
    },
    {
        "type": "entities",
        "entities": [{"entity": "select.spooltap_bind_slot", "name": "Slot"}],
    },
    {
        "type": "button",
        "name": "Bind Tag to Slot",
        "icon": "mdi:tray-plus",
        "show_state": False,
        "tap_action": _press("button.spooltap_bind_slot"),
        "card_mod": {
            "style": "ha-card { --card-mod-icon-color: rgba(var(--rgb-green),1); }"
        },
    },
    {
        "type": "markdown",
        "content": (
            "{% set slots = state_attr('sensor.spooltap_slots','slots') or [] %}"
            "### AMS slot tags — {{ slots|selectattr('tag_uid')|list|count }}/"
            "{{ slots|count }} bound _(layout auto-pulled from Bambuddy)_\n\n"
            "| Slot | Bound | NFC tag |\n|---|:-:|---|\n"
            "{% for s in slots %}| {{ s.label }} | {{ 'Yes' if s.tag_uid else '—' }} | "
            "{{ (s.tag_uid[-14:] if s.tag_uid else '—') }} |\n{% endfor %}"
        ),
    },
]

_MODIFY_CARDS: list[dict[str, Any]] = [
    {
        "type": "markdown",
        "content": (
            "Load a spool (pick below, or scan its tag with no slot pending), edit, then "
            "**Save**. Deep edits (colour, cost, vendor) live in Bambuddy."
        ),
    },
    {
        "type": "horizontal-stack",
        "cards": [
            {
                "type": "entities",
                "entities": [
                    {"entity": "select.spooltap_mod_open_tag", "name": "Open by Tag"},
                    {"entity": "select.spooltap_mod_open_spool", "name": "Open by Spool"},
                ],
            },
            _refresh_button("amber"),
        ],
    },
    {
        "type": "markdown",
        "content": (
            "{% set sid = states('sensor.spooltap_mod_loaded')|int(0) %}{% if sid>0 %}"
            "{% set e='sensor.spooltap_spool_'~sid~'_info' %}**Spool #{{sid}}** — "
            "{{ state_attr(e,'color_name') or state_attr(e,'material') }} / "
            "{{ state_attr(e,'material') }} · **{{ state_attr(e,'remaining_grams')|int(0) }}g**"
            " left · tag {{ state_attr(e,'tag_uid') or '—' }} · slot "
            "{{ state_attr(e,'assigned_slot') or '—' }}{% else %}*No spool loaded — pick one "
            "above (or scan a spool tag with no slot pending).*{% endif %}"
        ),
    },
    {
        "type": "entities",
        "entities": [
            {"entity": "text.spooltap_mod_name", "name": "Name (→ colour name)"},
            {"entity": "select.spooltap_mod_material", "name": "Material"},
            {"entity": "number.spooltap_mod_core", "name": "Empty-spool / tare (g)"},
            {"entity": "number.spooltap_mod_gross", "name": "Weigh-in: gross on scale (g)"},
            {"entity": "number.spooltap_mod_net", "name": "Remaining (g)"},
        ],
        "title": "Edit loaded spool",
    },
    {
        "type": "markdown",
        "content": (
            "**Recertify workflow** — the fields above load the spool's *current* values, "
            "so first check **Remaining** against your scale: if it already matches, "
            "there's nothing to fix. To recertify, put the spool on the scale, type the "
            "**gross** reading, and hit **Save** — Bambuddy does the tare math (gross − "
            "core) and records the weigh-in time. _(Typing **Remaining** directly also "
            "works.)_ The certified weight can't be overwritten by the coarse AMS remain% "
            "sync; per-print tracking continues from it."
        ),
    },
    {
        "type": "horizontal-stack",
        "cards": [
            {
                "type": "button",
                "name": "Save",
                "icon": "mdi:content-save",
                "show_state": False,
                "tap_action": _press("button.spooltap_save"),
                "card_mod": {
                    "style": "ha-card { --card-mod-icon-color: rgba(var(--rgb-green),1); }"
                },
            },
            {
                "type": "button",
                "name": "Archive",
                "icon": "mdi:archive-arrow-down",
                "show_state": False,
                "tap_action": {
                    **_press("button.spooltap_archive"),
                    "confirmation": {
                        "text": "Archive this spool? Its NFC tag becomes free to recycle."
                    },
                },
                "card_mod": {
                    "style": "ha-card { --card-mod-icon-color: rgba(var(--rgb-red),1); }"
                },
            },
            {
                "type": "button",
                "name": "Close",
                "icon": "mdi:close-circle-outline",
                "show_state": False,
                "tap_action": _press("button.spooltap_close"),
            },
        ],
    },
]

_SPOOLS_CARDS: list[dict[str, Any]] = [
    {
        "type": "markdown",
        "content": (
            "{% set ns = namespace(rows=[]) %}"
            "{% for s in states.sensor if s.entity_id.startswith('sensor.spooltap_spool_') "
            "and s.state not in ['unavailable','unknown'] "
            "and not s.attributes.get('slicer_filament') %}"
            "{% set ns.rows = ns.rows + [s] %}{% endfor %}"
            "{% if ns.rows %}"
            "### No filament profile — {{ ns.rows|count }} spools\n"
            "These spools have no slicer profile linked, so an assign pushes a *generic* "
            "profile to the tray. Fix in Bambuddy: edit the spool → **Filament Profile**.\n\n"
            "| ID | Brand | Mat | Name |\n|--:|---|---|---|\n"
            "{% for s in ns.rows|sort(attribute='attributes.spool_id') %}"
            "| {{ s.attributes.spool_id }} | {{ s.attributes.brand or '—' }} | {{ s.state }} "
            "| {{ s.attributes.color_name or s.name }} |\n{% endfor %}"
            "{% else %}**Every spool is linked to a filament profile.**{% endif %}"
        ),
    },
    {
        "type": "markdown",
        "content": (
            "{% set ns = namespace(rows=[]) %}"
            "{% for s in states.sensor if s.entity_id.startswith('sensor.spooltap_spool_') "
            "and s.state not in ['unavailable','unknown'] %}"
            "{% set ns.rows = ns.rows + [s] %}{% endfor %}"
            "### Inventory — {{ ns.rows|count }} spools\n\n"
            "| ID | Name | Mat | Left | Tag | Slot |\n|--:|---|---|--:|:-:|---|\n"
            "{% for s in ns.rows|sort(attribute='entity_id') %}| {{ s.attributes.spool_id }} "
            "| {{ s.attributes.color_name or s.name }} | {{ s.state }} | "
            "{{ s.attributes.remaining_grams }}g | "
            "{{ 'Yes' if s.attributes.get('tag_uid') else '—' }} | "
            "{{ s.attributes.assigned_slot or '—' }} |\n{% endfor %}"
        ),
    },
]

DASHBOARD_CONFIG: dict[str, Any] = {
    "views": [
        {
            "title": "SpoolTap",
            "path": "main",
            "icon": DASHBOARD_ICON,
            "type": "sections",
            "max_columns": 1,
            "sections": [
                {
                    "type": "grid",
                    "cards": [
                        {
                            "type": "horizontal-stack",
                            "cards": [_mode_chip(m) for m in _MODE_COLORS],
                        },
                        _HEADER_CARD,
                    ],
                },
                _mode_section("Assign", _ASSIGN_CARDS),
                _mode_section("Bind", _BIND_CARDS),
                _mode_section("Modify", _MODIFY_CARDS),
                _mode_section("Spools", _SPOOLS_CARDS),
            ],
        }
    ]
}


def _get_core_dashboards_collection(hass: HomeAssistant):
    """Core's LIVE DashboardsCollection, via the registered WS create handler.

    LovelaceData holds no collection reference (it is a local in lovelace's
    async_setup), so the only handle is the bound WS handler — the same object
    the frontend's own dashboards UI mutates. Returns None when unreachable.
    """
    from homeassistant.components.lovelace.dashboard import DashboardsCollection

    try:
        handler, _ = hass.data["websocket_api"]["lovelace/dashboards/create"]
        ws = handler.__wrapped__.__wrapped__.__self__  # require_admin -> async_response
        coll = ws.storage_collection
    except (KeyError, AttributeError):
        return None
    return coll if isinstance(coll, DashboardsCollection) else None


async def async_ensure_dashboard(hass: HomeAssistant, *, force: bool = False) -> bool:
    """Create the SpoolTap dashboard if missing; overwrite its config when force.

    Returns True when the dashboard exists (created or already present) and, if
    created/forced, its config was saved. Never raises to the caller's setup path
    — errors are logged and False is returned (the install_dashboard service is
    the retry lever).
    """
    try:
        from homeassistant.components import frontend
        from homeassistant.components.lovelace import _register_panel
        from homeassistant.components.lovelace.const import LOVELACE_DATA, MODE_STORAGE
        from homeassistant.components.lovelace.dashboard import (
            DashboardsCollection,
            LovelaceStorage,
        )

        lovelace = hass.data.get(LOVELACE_DATA)
        if lovelace is None:
            _LOGGER.warning("dashboard install skipped: lovelace not set up")
            return False

        existed = DASHBOARD_URL_PATH in lovelace.dashboards
        if not existed:
            coll = _get_core_dashboards_collection(hass)
            own_instance = coll is None
            if own_instance:
                # Fallback: our own collection instance persists the registry entry
                # but core's CHANGE_ADDED listener won't fire — register the storage
                # + panel by hand. (Core's instance could clobber the registry file
                # on a later save of its own; install_dashboard recovers.)
                _LOGGER.warning(
                    "dashboard install: core dashboards collection unreachable, "
                    "using fallback instance"
                )
                coll = DashboardsCollection(hass)
                await coll.async_load()
            item = next(
                (
                    i
                    for i in coll.async_items()
                    if i.get("url_path") == DASHBOARD_URL_PATH
                ),
                None,
            )
            if item is None:
                item = await coll.async_create_item(
                    {
                        "url_path": DASHBOARD_URL_PATH,
                        "title": DASHBOARD_TITLE,
                        "icon": DASHBOARD_ICON,
                        "show_in_sidebar": True,
                        "require_admin": False,
                    }
                )
            if DASHBOARD_URL_PATH not in lovelace.dashboards:
                # only reachable on the fallback path (no core listener ran)
                lovelace.dashboards[DASHBOARD_URL_PATH] = LovelaceStorage(hass, item)
                if not frontend.async_panel_exists(hass, DASHBOARD_URL_PATH):
                    _register_panel(hass, DASHBOARD_URL_PATH, MODE_STORAGE, item, False)

        if existed and not force:
            return True  # never overwrite a dashboard the user may have customized
        await lovelace.dashboards[DASHBOARD_URL_PATH].async_save(DASHBOARD_CONFIG)
        _LOGGER.info(
            "SpoolTap dashboard %s at /%s",
            "refreshed" if existed else "created",
            DASHBOARD_URL_PATH,
        )
        return True
    except Exception:  # noqa: BLE001 — internal lovelace APIs; never break setup
        _LOGGER.exception(
            "SpoolTap dashboard auto-install failed; run spooltap.install_dashboard "
            "to retry, or add the dashboard manually (see DEPLOY.md)"
        )
        return False
